import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import sitemap from 'vite-plugin-sitemap'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    sitemap({
      hostname: 'https://bccreative.agency',
      generateRobotsTxt: true,
      dynamicRoutes: [
        // ── Main Pages ─────────────────────────────────────────────────────
        '/',
        '/about',
        '/contact',
        '/blog',

        // ── Service Pages ─────────────────────────────────────────────────
        '/hizmetler/seo',
        '/hizmetler/google-ads',
        '/hizmetler/sosyal-medya',
        '/hizmetler/web-tasarim',
        '/hizmetler/produksiyon',
        '/hizmetler/drone-cekim',
        '/hizmetler/fotograf-video',

        // ── Blog Posts ────────────────────────────────────────────────────
        '/blog/kktcde-seo-nasil-yapilir',
        '/blog/kktc-google-ads-rehberi',
        '/blog/kktc-sosyal-medya-yonetimi',
        '/blog/kktc-web-tasarim-rehberi',
        '/blog/kktc-meta-ads-facebook-instagram-reklam',
        '/blog/kktc-icerik-pazarlamasi',
        '/blog/kktc-google-my-business-optimizasyonu',
        '/blog/kktc-tiktok-stratejisi',
        '/blog/kktc-video-pazarlama-youtube',
        '/blog/kktc-dijital-pazarlama-rakip-analizi',
        '/blog/kktc-whatsapp-business-pazarlama',
        '/blog/kktc-turizm-dijital-pazarlama',
        '/blog/kktc-restoran-kafe-dijital-pazarlama',
        '/blog/kktc-influencer-pazarlama',
        '/blog/kktc-landing-page-optimizasyonu',
        '/blog/kktc-marka-kimligi-ve-tasarim',
        '/blog/kktc-e-ticaret-rehberi',
        '/blog/kktc-gayrimenkul-yabanci-aliciya-ulasma',
        '/blog/kktc-dijital-pazarlama-rakip-analizi-ileri',
        '/blog/kktc-gayrimenkul-dijital-pazarlama-rehberi',
        '/blog/kktc-yerel-seo-stratejileri-harita-paket',
        '/blog/kktc-b2b-linkedin-pazarlama-stratejileri',
        '/blog/kktc-isletmeleri-icin-e-posta-pazarlama-otomasyonu',
        '/blog/kktc-isletmeleri-icin-google-ads-performans-max-kampanyalari',
        '/blog/kktc-web-tasarim-kullanici-deneyimi-ux-onemi',
        '/blog/kktc-gelir-ortakligi-pazarlama-rehberi',
        '/blog/kktc-isletmeleri-icin-yapay-zeka-pazarlama-donusumu',
        '/blog/kktc-mobil-pazarlama-musteriye-ulasmanin-yeni-yolu',
        '/blog/kktc-e-ticaret-google-analytics-4-veri-analizi',
        '/blog/kktc-marka-stratejisi-podcast-ile-otorite-insasi',
        '/blog/kktc-yerel-isletmeler-icin-citation-backlink-insasi',
        '/blog/kktc-e-ticaret-lojistik-odeme-cozumleri',
        '/blog/kktc-markalari-icin-kullanici-uretimi-icerik-ugc-gucu',
        '/blog/kktc-isletmeleri-icin-google-ads-remarketing-taktikleri',
        '/blog/kktc-turizm-isletmesi-dijital-musteri-yolculugu-haritasi',
        '/blog/kktc-drone-cekimi-emlak-turizm-girne',
        '/blog/kktc-sosyal-medya-icerik-takvimi-girne',
        '/blog/sosyal-medya-yonetimi-lefko-a-kktc',
        '/blog/kktc-meta-ads-facebook-instagram-reklam-yonetimi',
        '/blog/kktc-e-posta-pazarlama-otomasyonu-girne',
        '/blog/sosyal-medya-icerik-takvimi-kktc',
        '/blog/google-ads-kampanya-yonetimi-girne',
        '/blog/sosyal-medya-icerik-takvimi-kktc-markalar',
        '/blog/kktc-e-ticaret-seo-urun-sayfasi-optimizasyonu',
        '/blog/e-ticaret-seo-urun-sayfasi-optimizasyonu-kktc',
        '/blog/sosyal-medya-icerik-takvimi-kktc-turizm',
        '/blog/sosyal-medya-icerik-takvimi-lefko-a-kktc',
        '/blog/sosyal-medya-icerik-takvimi-kktc-turizm-isletmeleri',
        '/blog/kktc-instagram-hesap-yonetimi-girne',
        '/blog/kktc-sms-pazarlama-whatsapp-business-girne',
        '/blog/kktc-outdoor-reklam-tasarimi-billboard-tabela-girne',
        '/blog/instagram-hesap-yonetimi-lefko-a-kktc',
        '/blog/kktc-e-posta-pazarlama-otomasyonu-rehberi',
        '/blog/sosyal-medya-icerik-takvimi-gazimagusa-kktc',
        '/blog/kktc-tiktok-reklam-stratejileri-gencler',
        '/blog/kktc-influencer-pazarlama-stratejisi-girne',
        '/blog/kktc-video-prod-ksiyon-reklam-filmi-stratejileri',
        '/blog/kktc-youtube-reklam-stratejileri-girne',
        '/blog/kktc-sosyal-medya-yonetimi-marka-itibari',
        '/blog/sosyal-medya-yonetimi-kktc-restoran-kafe',
        '/blog/kktc-logo-tasarimi-marka-kimligi-girne',
        '/blog/linkedin-reklam-kktc-b2b-pazarlama',
        '/blog/kktc-reklam-butcesi-optimizasyonu-roas-hesaplama-girne',
        '/blog/kktc-pazar-arastirmasi-rakip-analizi-girne',
        '/blog/kktc-programatik-reklamcilik-veri-odakli-pazarlama-girne',
        '/blog/kktc-kurumsal-kimlik-tasarimi-girne-lefkoa',
        '/blog/kktc-sosyal-medya-gorsel-tasarim-rehberi-girne',
      ],
    }),
  ],
})
